/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ithembarayofhope;

/**
 *
 * @author Sanele
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }
    
    public static String strRole;
    frmLogin frmLogin = new frmLogin();
    SQLExecutingMethods sqlMethods = new SQLExecutingMethods();
    
    public void mUserAccessControl() {
        if(strRole.equals("Client")) {
            mnuSearch.setVisible(false);
            mnuPolicyCovers.setVisible(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu2 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        dpMain = new javax.swing.JDesktopPane();
        mbMenuBar = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuItemLogout = new javax.swing.JMenuItem();
        mnuItemExit = new javax.swing.JMenuItem();
        mnuPolicyCovers = new javax.swing.JMenu();
        mnuItemManageCovers = new javax.swing.JMenuItem();
        mnuViews = new javax.swing.JMenu();
        mnuItemViewUsers = new javax.swing.JMenuItem();
        mnuItemViewBeneficiaries = new javax.swing.JMenuItem();
        mnuItemViewCovers = new javax.swing.JMenuItem();
        mnuItemViewPrincipalMembers = new javax.swing.JMenuItem();
        mnuRegistrations = new javax.swing.JMenu();
        mnuItemPrincipalPolicyRegistrations = new javax.swing.JMenuItem();
        mnuItemLoginAccountManagement = new javax.swing.JMenuItem();
        mnuItemBeneficiariesRegistration = new javax.swing.JMenuItem();
        mnuSearch = new javax.swing.JMenu();
        mnuItemSearch = new javax.swing.JMenuItem();

        jMenu2.setText("jMenu2");

        jMenu7.setText("jMenu7");

        jMenu8.setText("jMenu8");

        jMenu3.setText("jMenu3");

        jMenuItem8.setText("jMenuItem8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(990, 632));

        dpMain.setBackground(new java.awt.Color(102, 102, 102));
        dpMain.setMaximumSize(new java.awt.Dimension(990, 632));

        javax.swing.GroupLayout dpMainLayout = new javax.swing.GroupLayout(dpMain);
        dpMain.setLayout(dpMainLayout);
        dpMainLayout.setHorizontalGroup(
            dpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
        );
        dpMainLayout.setVerticalGroup(
            dpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
        );

        mnuFile.setText("File");

        mnuItemLogout.setText("Logout");
        mnuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemLogoutActionPerformed(evt);
            }
        });
        mnuFile.add(mnuItemLogout);

        mnuItemExit.setText("Exit");
        mnuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemExitActionPerformed(evt);
            }
        });
        mnuFile.add(mnuItemExit);

        mbMenuBar.add(mnuFile);

        mnuPolicyCovers.setText("Policy Covers");

        mnuItemManageCovers.setText("Manage Covers");
        mnuItemManageCovers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemManageCoversActionPerformed(evt);
            }
        });
        mnuPolicyCovers.add(mnuItemManageCovers);

        mbMenuBar.add(mnuPolicyCovers);

        mnuViews.setText("Views");

        mnuItemViewUsers.setText("View Users");
        mnuItemViewUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemViewUsersActionPerformed(evt);
            }
        });
        mnuViews.add(mnuItemViewUsers);

        mnuItemViewBeneficiaries.setText("View Beneficiaries");
        mnuItemViewBeneficiaries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemViewBeneficiariesActionPerformed(evt);
            }
        });
        mnuViews.add(mnuItemViewBeneficiaries);

        mnuItemViewCovers.setText("View Covers");
        mnuItemViewCovers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemViewCoversActionPerformed(evt);
            }
        });
        mnuViews.add(mnuItemViewCovers);

        mnuItemViewPrincipalMembers.setText("View Members");
        mnuItemViewPrincipalMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemViewPrincipalMembersActionPerformed(evt);
            }
        });
        mnuViews.add(mnuItemViewPrincipalMembers);

        mbMenuBar.add(mnuViews);

        mnuRegistrations.setText("Registrations");

        mnuItemPrincipalPolicyRegistrations.setText("Principal Policy Registration");
        mnuItemPrincipalPolicyRegistrations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemPrincipalPolicyRegistrationsActionPerformed(evt);
            }
        });
        mnuRegistrations.add(mnuItemPrincipalPolicyRegistrations);

        mnuItemLoginAccountManagement.setText("Login Account Management");
        mnuItemLoginAccountManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemLoginAccountManagementActionPerformed(evt);
            }
        });
        mnuRegistrations.add(mnuItemLoginAccountManagement);

        mnuItemBeneficiariesRegistration.setText("Beneficiaries Registration");
        mnuItemBeneficiariesRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemBeneficiariesRegistrationActionPerformed(evt);
            }
        });
        mnuRegistrations.add(mnuItemBeneficiariesRegistration);

        mbMenuBar.add(mnuRegistrations);

        mnuSearch.setText("Search");

        mnuItemSearch.setText("Search by Alphabet");
        mnuItemSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemSearchActionPerformed(evt);
            }
        });
        mnuSearch.add(mnuItemSearch);

        mbMenuBar.add(mnuSearch);

        setJMenuBar(mbMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(dpMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(dpMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItemViewUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemViewUsersActionPerformed
        switch(strRole) {
            case "Client":
                frmViewDatabaseTable frmViewMyUserDetails = new frmViewDatabaseTable("SELECT Username, Password, Role FROM Users_Login WHERE ID ="+frmLogin.mGetLoginAccount());
                frmViewMyUserDetails.setLocationRelativeTo(null);
                frmViewMyUserDetails.setAlwaysOnTop(true);
                frmViewMyUserDetails.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                frmViewMyUserDetails.setVisible(true);
                break;
            case "Administrator":
                frmViewDatabaseTable frmViewUsers = new frmViewDatabaseTable("SELECT Username, Role FROM Users_Login");
                frmViewUsers.setLocationRelativeTo(null);
                frmViewUsers.setAlwaysOnTop(true);
                frmViewUsers.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                frmViewUsers.setVisible(true);
                break;
        }
    }//GEN-LAST:event_mnuItemViewUsersActionPerformed

    private void mnuItemManageCoversActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemManageCoversActionPerformed
        frmCovers frmCovers = new frmCovers();
        frmCovers.setLocationRelativeTo(null);
        frmCovers.setAlwaysOnTop(true);
        frmCovers.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        frmCovers.setVisible(true);
    }//GEN-LAST:event_mnuItemManageCoversActionPerformed

    private void mnuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemLogoutActionPerformed
        strRole = null;
        frmLogin.mSetLoginAccount(null);
        frmLogin.setLocationRelativeTo(null);
        frmLogin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuItemLogoutActionPerformed

    private void mnuItemLoginAccountManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemLoginAccountManagementActionPerformed
        frmRegister frmReg = new frmRegister();
        frmReg.setLocationRelativeTo(null);
        frmReg.setAlwaysOnTop(true);
        frmReg.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        frmReg.mHideReturnButton();
        frmReg.setVisible(true);
        if(frmLogin.mGetLoginAccount() == null) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_mnuItemLoginAccountManagementActionPerformed

    private void mnuItemPrincipalPolicyRegistrationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemPrincipalPolicyRegistrationsActionPerformed
        switch(strRole) {
            case "Client":
                frmPolicyRegistrations frmPolicyReg = new frmPolicyRegistrations();
                frmPolicyReg.setLocationRelativeTo(null);
                frmPolicyReg.setAlwaysOnTop(true);
                frmPolicyReg.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                frmPolicyReg.setVisible(true);
                break;
                
            case "Administrator":
                frmSelectClient frmSelectClient = new frmSelectClient();
                frmSelectClient.setLocationRelativeTo(null);
                frmSelectClient.setAlwaysOnTop(true);
                frmSelectClient.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                frmSelectClient.setVisible(true);
                break;
        }
    }//GEN-LAST:event_mnuItemPrincipalPolicyRegistrationsActionPerformed

    private void mnuItemBeneficiariesRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemBeneficiariesRegistrationActionPerformed
        frmBeneficiaries frmBeneficiary = new frmBeneficiaries();
        frmBeneficiary.setLocationRelativeTo(null);
        frmBeneficiary.setAlwaysOnTop(true);
        frmBeneficiary.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        frmBeneficiary.setVisible(true);
    }//GEN-LAST:event_mnuItemBeneficiariesRegistrationActionPerformed

    private void mnuItemViewBeneficiariesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemViewBeneficiariesActionPerformed
        switch(strRole) {
            case "Client":
                frmViewDatabaseTable frmViewMyBeneficiaries = new frmViewDatabaseTable(
                        "SELECT IDNum, FName, LName, Relationship, PM_ID_Num FROM Beneficiaries WHERE PM_ID_Num ='"+
                                sqlMethods.mTableField("SELECT ID_Num FROM Principal_Member WHERE Login ="+frmLogin.mGetLoginAccount())+"'");
                frmViewMyBeneficiaries.setLocationRelativeTo(null);
                frmViewMyBeneficiaries.setAlwaysOnTop(true);
                frmViewMyBeneficiaries.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                frmViewMyBeneficiaries.setVisible(true);
                break;
            case "Administrator":
                frmViewDatabaseTable frmViewBeneficiaries = new frmViewDatabaseTable("SELECT IDNum, FName, LName, Relationship, PM_ID_Num FROM Beneficiaries");
                frmViewBeneficiaries.setLocationRelativeTo(null);
                frmViewBeneficiaries.setAlwaysOnTop(true);
                frmViewBeneficiaries.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                frmViewBeneficiaries.setVisible(true);
                break;
        }
    }//GEN-LAST:event_mnuItemViewBeneficiariesActionPerformed

    private void mnuItemViewCoversActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemViewCoversActionPerformed
        frmViewDatabaseTable frmViewCovers = new frmViewDatabaseTable("SELECT ID, CoverAmount, Category, Premium FROM Covers");
        frmViewCovers.setLocationRelativeTo(null);
        frmViewCovers.setAlwaysOnTop(true);
        frmViewCovers.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        frmViewCovers.setVisible(true);
    }//GEN-LAST:event_mnuItemViewCoversActionPerformed

    private void mnuItemViewPrincipalMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemViewPrincipalMembersActionPerformed
        switch(strRole) {
            case "Client":
                frmViewDatabaseTable frmViewMyPrincipalMemberDetails = new frmViewDatabaseTable(
                        "SELECT ID_Num, LName, FName, DOB, Address, Tel, Email, CoverID FROM Principal_Member WHERE Login ="+frmLogin.mGetLoginAccount());
                frmViewMyPrincipalMemberDetails.setLocationRelativeTo(null);
                frmViewMyPrincipalMemberDetails.setAlwaysOnTop(true);
                frmViewMyPrincipalMemberDetails.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                frmViewMyPrincipalMemberDetails.setVisible(true);
                break;
            case "Administrator":
                frmViewDatabaseTable frmViewPrincipalMembers = new frmViewDatabaseTable("SELECT ID_Num, LName, FName, DOB, Address, Tel, Email, CoverID FROM Principal_Member");
                frmViewPrincipalMembers.setLocationRelativeTo(null);
                frmViewPrincipalMembers.setAlwaysOnTop(true);
                frmViewPrincipalMembers.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                frmViewPrincipalMembers.setVisible(true);
                break;
        }
    }//GEN-LAST:event_mnuItemViewPrincipalMembersActionPerformed

    private void mnuItemSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemSearchActionPerformed
        new SearchFilter(this).setVisible(true);
    }//GEN-LAST:event_mnuItemSearchActionPerformed

    private void mnuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuItemExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpMain;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuBar mbMenuBar;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuItemBeneficiariesRegistration;
    private javax.swing.JMenuItem mnuItemExit;
    private javax.swing.JMenuItem mnuItemLoginAccountManagement;
    private javax.swing.JMenuItem mnuItemLogout;
    private javax.swing.JMenuItem mnuItemManageCovers;
    private javax.swing.JMenuItem mnuItemPrincipalPolicyRegistrations;
    private javax.swing.JMenuItem mnuItemSearch;
    private javax.swing.JMenuItem mnuItemViewBeneficiaries;
    private javax.swing.JMenuItem mnuItemViewCovers;
    private javax.swing.JMenuItem mnuItemViewPrincipalMembers;
    private javax.swing.JMenuItem mnuItemViewUsers;
    private javax.swing.JMenu mnuPolicyCovers;
    private javax.swing.JMenu mnuRegistrations;
    private javax.swing.JMenu mnuSearch;
    private javax.swing.JMenu mnuViews;
    // End of variables declaration//GEN-END:variables

}
